version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "3000:80"
    environment:
      - VUE_APP_API_URL=https://api.your-username.github.io/api

  backend:
    build: ./backend
    container_name: dotnet_backend
    ports:
      - "5050:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=ProductWebsite;User Id=sa;Password=Ads12989;TrustServerCertificate=True

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    hostname: your-username.github.io
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
